import { Client, PrivateKey, createAPISig, KeyInfo, UserAuth, ThreadID, Update } from '@textile/hub';

/**
 * Centralized Textile Hub Auth
 *
 * There's two ways to do auth with the centralized Textile Hub. They generally follow typical web2 authentication schemes with key/secret pairs
 * being used to request access via a token.
 * 1. "Dev mode" – This makes it so the Hub only requires your user key and does not require your user group secret when interacting with the hub
 *                 client and the hub server. You only require your user key in order to "authenticate" and get a token for operations.
 * 2. "Prod mode" – This requires your user group secret and your user key to be able to authenticate and get a token for operations on the client
 *                  and server.
 *
 * This demo uses "Dev mode" and is not intended to be used in production. Since this is a free account and there's nothing security-related within
 * this demo app it's not a big deal to just share within the team. We can also make "Organizations" within the Hub and have multiple users with multiple
 * key/secret pairs that way.
 *
 * Docs:
 * https://docs.textile.io/hub/apis/
 * https://docs.textile.io/hub/apis/#non-signing-user-group-keys
 */

/**
 * Storage in ThreadDB
 *
 * The hierarchy of ThreadDB is similar to what you'd expect to find in MongoDB.
 * * A Thread can contain multiple Databases.
 * * A Database can contain multiple Collections. (Tables)
 * * A Collection can contain multiple Instances. (Rows)
 *
 * As far as I can tell, Storage in ThreadDB is scoped to a user group, so if you do not have access to the user group's key/secret pair you cannot access
 * the data in that user groups' Threads.
 */

// KeyInfo
export const keyInfo: KeyInfo = {
    key: 'blyf6xqz42ww57wgxxjbrmvq5aa',
};

// const auth: UserAuth = {
//     ...keyInfo,
//     // ...createAPISig('bzo7c3pnbxqs56xx4zrgnbeucyqdmiiqaamhwemi').then((result) => result),
// };

export type Astronaut = {
    name: string;
    missions: number;
    _id: string;
};

// Since we are using unsigned keys we don't need to pass a secret and set a signature
export async function setupClient(auth: KeyInfo) {
    const client = await Client.withKeyInfo(auth);
    const token = await client.getToken(
        PrivateKey.fromString('bbaareieq5pk4mua5mb447k5ft3gy4qsdjzx5y6wwiwik4kp6gdsitrfmzu'),
    );

    return client;
}

async function createTable(client: Client) {
    // Create a new DB with the name NASA and no id. If we don't pass an ID it gets autogenerated.
    const threadId = await client.newDB(undefined, 'nasa');

    // This will be an instance of "astronauts" collection in the "nasa" thread
    const lightyear = {
        name: 'Lightyear',
        missions: 5,
        _id: '',
    };

    const buzz = {
        name: 'Buzz',
        missions: 5,
        _id: '',
    };

    // Create a new collection from an object. We name it "astronauts" and generate the schema
    // from the buzz object
    await client.newCollectionFromObject(threadId, buzz, { name: 'astronauts' });

    // Store the buzz object in the new collection as an instance (row)
    const instanceIds = await client.create(threadId, 'astronauts', [buzz, lightyear]);
    console.log(instanceIds);

    return {
        threadId,
        instanceIds,
    };
}

export async function createAstronaut(client: Client, astronaut: Astronaut) {
    const [newAstronautId] = await client.create(await getThreadId(client, 'nasa'), 'astronauts', [astronaut]);
    return newAstronautId;
}

export async function findAstronaut(client: Client, astronautId: string) {
    const threadId = await getThreadId(client, 'nasa');
    return await client.findByID<Astronaut>(threadId, 'astronauts', astronautId);
}

export async function deleteAstronaut(client: Client, astronautId: string) {
    const threadId = await getThreadId(client, 'nasa');
    await client.delete(threadId, 'astronauts', [astronautId]);
    return astronautId;
}

export async function findAllAstronauts(client: Client) {
    const threadId = await getThreadId(client, 'nasa');
    return await client.find<Astronaut>(threadId, 'astronauts', {});
}

async function listCollections(client: Client) {
    const threadId = await getThreadId(client, 'nasa');
    return await client.listCollections(threadId);
}

export async function getThreadId(client: Client, threadName: string | 'nasa') {
    const thread = await client.getThread(threadName);
    return ThreadID.fromString(thread.id);
}

export async function startListener(
    client: Client,
    threadID: ThreadID,
    callback: (astronaut: Update<Astronaut>) => void,
) {
    const filters = [{ actionTypes: ['CREATE', 'DELETE'] }];
    return client.listen<Astronaut>(threadID, filters, callback);
}

// const { threadId } = await createTable(client);
// const astronautId = await createAstronaut(client, {
//     name: 'Carl',
//     missions: 5000,
//     _id: '',
// });

// console.log(await findAllAstronauts(client));
